---
apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  namespace: argocd
  labels:
    run: my-nginx
spec:
  type: LoadBalancer
  selector:
    run: my-nginx
  ports:
  - port: 80
    protocol: TCP
